@startuml
skinparam classAttributeIconSize 0

class OrderService {
  +CreateOrder()
}

class PaymentService {
  +Pay()
}

class Logger {
  -static instance: Logger
  -Logger()
  +static Instance: Logger
  +Log(message: string)
}

OrderService --> Logger : Logger.Instance.Log()
PaymentService --> Logger : Logger.Instance.Log()

@enduml
