---
title: Mediator class diagram
---
classDiagram
    class Mediator{
      <<interface>>
      +notify(sender, event)
    }

    class Colleague{
      #mediator : Mediator
      +send(event)
      +receive(event)
    }

    Mediator <-- Colleague
    Mediator <|-- ConcreteMediator
    Colleague <|-- ConcreteComponent1
    Colleague <|-- ConcreteComponent2

    class ConcreteMediator{
      -component1 : ConcreteComponent1
      -component2 : ConcreteComponent2
      +setComponent1(c1)
      +setComponent2(c2)
      +notify(sender, event)
    }

    class ConcreteComponent1{
      +doA()
      +doB()
    }

    class ConcreteComponent2{
      +doC()
      +doD()
    }

    ConcreteMediator --> ConcreteComponent1
    ConcreteMediator --> ConcreteComponent2
