---
title: Adapter class diagram
---
classDiagram
  class Target  { 
    <<interface>>
    +req() String
  }

  class Service {
    +wtf() String
  }

  Target <|-- Adapter
  Service <-- Adapter
  class Adapter {
    -adaptee : Service

    +Adapter()
    +req() String
  }